stateDiagram-v2
    [*] --> DisplayingOff : wanted = DISPLAY_OFF
    [*] --> DisplayingArmNotZeroed : wanted = DISPLAY_ROBOT_ARM_NOT_ZEROED
    [*] --> DisplayingPoseReset : wanted = DISPLAY_POSE_RESET
    [*] --> DisplayingArmZeroed : wanted = DISPLAY_ROBOT_ARM_ZEROED
    [*] --> DisplayingPhysicallyReady : wanted = DISPLAY_ROBOT_IS_PHYSICALLY_READY_FOR_MATCH
    [*] --> DisplayingPoseBased : wanted = DISPLAY_POSE_BASED
    [*] --> DisplayingRotationBased : wanted = DISPLAY_ROTATION_BASED
    [*] --> DisplayingNotAtKickstand : wanted = DISPLAY_NOT_AT_KICKSTAND_POSITION
    [*] --> DisplayingZeroAction : wanted = DISPLAY_ROBOT_ZERO_ACTION
    [*] --> DisplayingReadyForMatch : wanted = DISPLAY_READY_FOR_MATCH
    [*] --> DisplayingIntakingAlgae : wanted = DISPLAY_INTAKING_ALGAE
    [*] --> DisplayingHoldingAlgae : wanted = DISPLAY_HOLDING_ALGAE
    [*] --> DisplayingAlignToProcessor : wanted = DISPLAY_ALIGN_TO_PROCESSOR
    [*] --> DisplayingScoreProcessor : wanted = DISPLAY_SCORE_PROCESSOR
    [*] --> DisplayingAlignToBarge : wanted = DISPLAY_ALIGN_TO_BARGE
    [*] --> DisplayingScoreBarge : wanted = DISPLAY_SCORE_BARGE
    [*] --> DisplayingIntakingCoral : wanted = DISPLAY_INTAKING_CORAL
    [*] --> DisplayingIntakingCoralHorizontal : wanted = DISPLAY_INTAKING_CORAL_HORIZONTAL
    [*] --> DisplayingHoldingCoralPoseBased : wanted = DISPLAY_HOLDING_CORAL_POSE_BASED
    [*] --> DisplayingHoldingCoralRotationBased : wanted = DISPLAY_HOLDING_CORAL_ROTATION_BASED
    [*] --> TagNotSeen : wanted = TAG_NOT_SEEN
    [*] --> DisplayingAlignToTargetL1 : wanted = DISPLAY_ALIGN_TO_TARGET_L_ONE
    [*] --> DisplayingAlignToTargetL2 : wanted = DISPLAY_ALIGN_TO_TARGET_L_TWO
    [*] --> DisplayingAlignToTargetL3 : wanted = DISPLAY_ALIGN_TO_TARGET_L_THREE
    [*] --> DisplayingAlignToTargetL4 : wanted = DISPLAY_ALIGN_TO_TARGET_L_FOUR
    [*] --> DisplayingCanScoreL1 : wanted = DISPLAY_CAN_SCORE_L_ONE
    [*] --> DisplayingCanScoreL2 : wanted = DISPLAY_CAN_SCORE_L_TWO
    [*] --> DisplayingCanScoreL3 : wanted = DISPLAY_CAN_SCORE_L_THREE
    [*] --> DisplayingCanScoreL4 : wanted = DISPLAY_CAN_SCORE_L_FOUR
    [*] --> DisplayingClimbAlign : wanted = DISPLAY_CLIMB_ALIGN
    [*] --> DisplayingClimbAutomated : wanted = DISPLAY_CLIMB_AUTOMATED
    [*] --> DisplayingControllerActive : wanted = DISPLAY_CONTROLLERS_ACTIVE
