stateDiagram-v2
    [*] --> Home : wanted = HOME
    [*] --> Stopped : wanted = STOPPED
    [*] --> ArmUp : wanted = ARM_UP
    [*] --> MarkPunch : wanted = MARK_PUNCH
    [*] --> ForceRelocalizeLeft : wanted = FORCE_RELOCALIZE_LEFT
    [*] --> ForceRelocalizeRight : wanted = FORCE_RELOCALIZE_RIGHT
    [*] --> IntakeCoralFromGround : wanted = INTAKE_CORAL_FROM_GROUND
    [*] --> IntakeCoralFromGroundHorizontally : wanted = INTAKE_CORAL_FROM_GROUND_HORIZONTALLY
    [*] --> IntakeCoralFromMark : wanted = INTAKE_CORAL_FROM_MARK
    [*] --> IntakeCoralFromStation : wanted = INTAKE_CORAL_FROM_STATION_STRAIGHT
    [*] --> NoPieceTeleop : wanted = DEFAULT_STATE [no piece + teleop]
    [*] --> NoPieceAuto : wanted = DEFAULT_STATE [no piece + auto]
    [*] --> HoldingCoralTeleop : wanted = DEFAULT_STATE [has coral + teleop]
    [*] --> HoldingCoralAuto : wanted = DEFAULT_STATE [has coral + auto]
    [*] --> HoldingAlgae : wanted = DEFAULT_STATE [has algae]
    [*] --> ScoreTeleopL1ManualAlign : wanted = SCORE_L1_MANUAL_ALIGN [teleop]
    [*] --> ScoreAutoL1 : wanted = SCORE_L1_MANUAL_ALIGN [auto]
    [*] --> ScoreL1LeftBase : wanted = SCORE_L1_LEFT_BASE
    [*] --> ScoreL1RightBase : wanted = SCORE_L1_RIGHT_BASE
    [*] --> ScoreL1LeftTop : wanted = SCORE_L1_LEFT_TOP
    [*] --> ScoreL1RightTop : wanted = SCORE_L1_RIGHT_TOP
    [*] --> ScoreLeftTeleopL2 : wanted = SCORE_LEFT_L2 [teleop]
    [*] --> ScoreLeftAutoL2 : wanted = SCORE_LEFT_L2 [auto]
    [*] --> ScoreLeftTeleopL3 : wanted = SCORE_LEFT_L3 [teleop]
    [*] --> ScoreLeftAutoL3 : wanted = SCORE_LEFT_L3 [auto]
    [*] --> ScoreLeftTeleopL4 : wanted = SCORE_LEFT_L4 [teleop]
    [*] --> ScoreLeftAutoL4 : wanted = SCORE_LEFT_L4 [auto]
    [*] --> ScoreRightTeleopL2 : wanted = SCORE_RIGHT_L2 [teleop]
    [*] --> ScoreRightAutoL2 : wanted = SCORE_RIGHT_L2 [auto]
    [*] --> ScoreRightTeleopL3 : wanted = SCORE_RIGHT_L3 [teleop]
    [*] --> ScoreRightAutoL3 : wanted = SCORE_RIGHT_L3 [auto]
    [*] --> ScoreRightTeleopL4 : wanted = SCORE_RIGHT_L4 [teleop]
    [*] --> ScoreRightAutoL4 : wanted = SCORE_RIGHT_L4 [auto]
    [*] --> ManualL1 : wanted = MANUAL_L1
    [*] --> ManualL2 : wanted = MANUAL_L2
    [*] --> ManualL3 : wanted = MANUAL_L3
    [*] --> ManualL4 : wanted = MANUAL_L4
    [*] --> IntakeAlgaeFromHP : wanted = INTAKE_ALGAE_FROM_HP
    [*] --> IntakeAlgaeFromReef : wanted = INTAKE_ALGAE_FROM_REEF
    [*] --> IntakeAlgaeFromGround : wanted = INTAKE_ALGAE_FROM_GROUND
    [*] --> IntakeAlgaeFromMark : wanted = INTAKE_ALGAE_FROM_MARK
    [*] --> MoveAlgaeToNetPosition : wanted = MOVE_ALGAE_TO_NET_POSITION
    [*] --> ScoreAlgaeInNet : wanted = SCORE_ALGAE_IN_NET
    [*] --> MoveAlgaeToProcessorPosition : wanted = MOVE_ALGAE_TO_PROCESSOR_POSITION
    [*] --> ScoreAlgaeInProcessor : wanted = SCORE_ALGAE_IN_PROCESSOR
    [*] --> Climb : wanted = CLIMB
